# Generated by Django 3.0.3 on 2020-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwold',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=123, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
    ]
