# Generated by Django 3.0.3 on 2020-02-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
