# Generated by Django 3.0.3 on 2020-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_user_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
