# Generated by Django 3.0.3 on 2020-02-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200208_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=128),
        ),
    ]
